set(CURR_CMAKE_PREFIX_PATH "${CMAKE_CURRENT_LIST_DIR}")

set(OLD_ZLIB_DIR "${ZLIB_DIR}")
set(OLD_CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}")

unset(ZLIB_DIR CACHE)
unset(ZLIB_DIR)

list(REMOVE_ITEM CMAKE_PREFIX_PATH "${CURR_CMAKE_PREFIX_PATH}")

find_package(ZLIB REQUIRED CONFIG
	COMPONENTS static
	PATHS "${CMAKE_PREFIX_PATH}"
    NO_DEFAULT_PATH
    NO_PACKAGE_ROOT_PATH
    NO_CMAKE_PACKAGE_REGISTRY
    NO_SYSTEM_ENVIRONMENT_PATH
    NO_CMAKE_SYSTEM_PACKAGE_REGISTRY
)

set(ZLIB_DIR "${OLD_ZLIB_DIR}")
set(CMAKE_PREFIX_PATH "${OLD_CMAKE_PREFIX_PATH}")

set(CACHE{ZLIB_DIR} FORCE VALUE "${OLD_ZLIB_DIR}")

if(NOT TARGET ZLIB::ZLIB)
	add_library(ZLIB::ZLIB ALIAS ZLIB::ZLIBSTATIC)
endif()

